version: "1"

stages:
  - id: scope
    template: scope.md
    inputs:
      - inputs/sample_rfc.md
    outputs:
      - scope.md

  - id: review
    template: review.md
    inputs:
      - inputs/sample_rfc.md
      - scope.md
    outputs:
      - review.md

  - id: skeptic
    template: skeptic.md
    inputs:
      - inputs/sample_rfc.md
      - review.md
    outputs:
      - skeptic_findings.md

  - id: report
    template: report.md
    inputs:
      - inputs/sample_rfc.md
      - review.md
      - skeptic_findings.md
    outputs:
      - final_review.md
