name: "code-review"
version: "1.0"
description: "A 5-stage, staged and gated code review workflow designed to converge."

stages:
  - id: scope
    name: Review Scope & Constraints
    type: spec
    intent: planning
    template: scope.md
    outputs: [scope.md]
    
  - id: architecture-pass
    name: Architecture Pass
    type: spec
    intent: review
    template: architecture-pass.md
    depends_on: [scope]
    inputs: [scope.md]
    outputs: [architecture-findings.md]
    
  - id: file-review
    name: File-Level Review
    type: spec
    intent: review
    template: file-review.md
    depends_on: [architecture-pass]
    inputs: [scope.md, architecture-findings.md]
    outputs: [file-findings.md]
    
  - id: skeptic-pass
    name: Skeptic Pass
    type: spec
    intent: review
    template: skeptic-pass.md
    depends_on: [file-review]
    inputs: [file-findings.md]
    outputs: [verified-findings.md]
    
  - id: report
    name: Final Review Report
    type: spec
    intent: documentation
    template: report.md
    depends_on: [skeptic-pass, scope]
    inputs: [scope.md, verified-findings.md]
    outputs: [review-report.md]
