name: "api-feature"
description: Accelerates API development with specification-driven design, implementation, and verification.
version: "1.1"

stages:
  - id: clarify
    name: Requirements Clarification
    type: spec
    intent: exploration
    template: clarify.md
    outputs: [requirements.md]
    
  - id: design
    name: API Design
    type: spec
    intent: decision
    template: design.md
    depends_on: [clarify]
    inputs: [requirements.md]
    outputs: [design.md]
    
  - id: decompose
    name: Task Breakdown
    type: decompose
    intent: planning
    template: decompose.md
    depends_on: [clarify, design]
    inputs: [requirements.md, design.md]
    outputs: [tasks.yaml]
    prompt:
      granularity: ticket
      max_tasks: 10
      
  - id: implementation
    name: Implementation
    type: task_prompt
    intent: execution
    template: implementation.md
    depends_on: [clarify, design, decompose]
    inputs: [requirements.md, design.md, tasks.yaml]
    source: decompose
    outputs: []

approvals:
  - stage: design
    role: architect
  - stage: design
    role: product
