name: "api-feature"
description: Accelerates API development with specification-driven design, implementation, and verification.
version: "1.0"

stages:
  - id: requirements
    name: Requirements Gathering
    type: spec
    intent: exploration
    template: templates/requirements.md
    outputs: [requirements.md]
    
  - id: design
    name: API Design
    type: spec
    intent: decision
    template: templates/design.md
    depends_on: [requirements]
    inputs: [requirements.md]
    outputs: [design.md]
    
  - id: decompose
    name: Task Breakdown
    type: decompose
    intent: planning
    template: templates/decompose.md
    depends_on: [design]
    inputs: [design.md]
    outputs: [tasks.yaml]
    prompt:
      granularity: ticket
      max_tasks: 10
      
  - id: implementation
    name: Implementation
    type: task_prompt
    intent: execution
    template: templates/implementation.md
    depends_on: [requirements, design, decompose]
    inputs: [requirements.md, design.md, tasks.yaml]
    source: decompose
    outputs: []

approvals:
  - stage: design
    role: architect
  - stage: design
    role: product
