name: "todo-cli-protocol"
version: "1.1"

stages:
  - id: clarify
    name: Requirements Clarification
    type: spec
    intent: exploration
    template: clarify.md
    outputs: [requirements.md]

  - id: design
    name: System Design
    type: spec
    template: design.md
    depends_on: [clarify]
    inputs: [requirements.md]
    outputs: [design.md]

  - id: breakdown
    name: Task Decomposition
    type: decompose
    template: decompose.md
    depends_on: [clarify, design]
    inputs: [requirements.md, design.md]
    outputs: [tasks.yaml]
    prompt:
      granularity: ticket
      max_tasks: 5

  - id: codes
    name: Task Implementation
    type: task_prompt
    template: implementation.md
    depends_on: [clarify, design, breakdown]
    inputs: [requirements.md, design.md, tasks.yaml]
    source: breakdown
