name: "todo-cli-protocol"
version: "1.0"

stages:
  - id: reqs
    name: Todo CLI Requirements
    type: spec
    template: templates/requirements.md
    outputs: [requirements.md]

  - id: design
    name: System Design
    type: spec
    template: templates/design.md
    depends_on: [reqs]
    inputs: [requirements.md]
    outputs: [design.md]

  - id: breakdown
    name: Task Decomposition
    type: decompose
    template: templates/decompose.md
    depends_on: [reqs, design]
    inputs: [requirements.md, design.md]
    outputs: [tasks.yaml]
    prompt:
      granularity: ticket
      max_tasks: 5

  - id: codes
    name: Task Implementation
    type: task_prompt
    template: templates/implementation.md
    depends_on: [reqs, design, breakdown]
    inputs: [requirements.md, design.md, tasks.yaml]
    source: breakdown
